Sales evidence search fields
haydenf/zoho-crm-react-js-typescript-google-maps-widget pull request #9
Opened 2020-07-14 11:14 UTC by haydenf

2020-07-17 00:06 UTC, johnEthicalTechnology requested changes
Let me know when you've done updating it and I'll check it again. Then we can merge master. I'll create a PR for my sales evidence filter.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/App.tsx
> +                    {widgetStateChange === 'sales' &&
Let's name this `SalesEvidenceFilter`. It's a clearer as to what it will be rendering.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/App.tsx
> +                    {widgetStateChange === 'baseFilter' &&
Make this `BaseFilter` for consistency.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/App.tsx
> +    const [widgetStateChange, setWidgetStateChange] = useState<string>('baseFilter')
Change `widgetStateChange` to `filterInUse`.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/SaleTypeDropdown.tsx
> +                placeholder={'All'}
Change this to `''` to be consistent with how they want the rest of the filters to be when not being used.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/SaleTypeDropdown.tsx
> +        { value: SaleTypeEnum.ALL, label: SaleTypeEnum.ALL },
Don't worry about having the ALL enum. If they want to have all of them they'll select all of the values. I've made it so that if they don't want to use this filter it'll default to an empty array that will be ignored in the filter function.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/ResultsTable.tsx
> +                        {uniqueResults.map((result, index) => {
This isn't declared anywhere. Was this meant to remove dupes?

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/SearchWidgetsWrapper.tsx
> +    function hideWidget (value: string) {
This isn't needed. Check the comment below to see what you can do instead.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/SearchWidgetsWrapper.tsx
> +                            <input name='radio' type="radio" checked={props.widgetStateChange === 'baseFilter'} onClick={() => hideWidget('baseFilter')}/>
You can change `onClick={() => hideWidget('baseFilter')}` to `onClick={() => props.setWidgetStateChange('baseFilter')}`

Likewise for the sales one.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/SearchWidgetsWrapper.tsx
> +            {props.widgetStateChange === 'sales' && props.searchParameters[0] &&
You can get rid of `&& props.searchParameters[0]` it's not needed.

Here it's just serving as a check to make sure that the search parameters exist. But they will always exist b/c they have default values.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/salesEvidenceSearch.tsx
> +                    }} placeholder="Default 0" type="number" tabIndex={6} />
Change the placeholder value to `Min` as per the UI designs Chris sent. Do the same for the others as well.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/salesEvidenceSearch.tsx
> +                    }} placeholder="Default 10000" type="number" tabIndex={6} />
Change the placeholder value to `Max` as per Chris's UI designs and the same with the others in the file.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/salesEvidenceSearch.tsx
> +                            dateSold: { min: changeDate, max: props.searchParameters.dateSold.min }
The `min` is meant to be `max`. Checkit: `max: props.searchParameters.dateSold.min` is meant to be `max: props.searchParameters.dateSold.max`

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/salesEvidenceSearch.tsx
> +                        console.log('this is the event from DatePicker type any', changeDate)
Remove the `console.log`.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/components/salesEvidenceSearch.tsx
> +                    <input className="minMaxSize border" id="buildArea" onChange={(e: ChangeEvent<HTMLInputElement>) => {
Change `id="buildArea"` to `id="buildAreaMin"`.

There are a few more of examples of this happening. Just check the rest to make sure you give id a unique string.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/types.ts
> +        min: 0,
I've changed some stuff in types in the sales evidence filter branch. We'll merge this into master and then merge my branch into master and I'll fix the conflicts then.

2020-07-17 00:06 UTC, johnEthicalTechnology commented on src/utils/salesEvidenceSortAndFilter.ts
> +// TODO - tsconfig replace CommonJS with esnext
This has changed a lot. You can probably just delete this file.

2020-07-17 04:43 UTC, haydenf commented on src/components/ResultsTable.tsx
> +                        {uniqueResults.map((result, index) => {
what do you mean?

2020-07-17 04:51 UTC, johnEthicalTechnology requested changes

2020-07-17 04:51 UTC, johnEthicalTechnology commented on src/App.tsx
> +                    {filterInUse === 'sales' &&
Change `sales` to `SalesEvidenceFilter`.

2020-07-17 04:57 UTC, johnEthicalTechnology commented on src/components/ResultsTable.tsx
> +                        {uniqueResults.map((result, index) => {
When I start the server it crashes b/c `uniqueResults` isn't declared anywhere in `ResultsTable`. Do you mean to use `props.results.map`? Or do you want to remove the dupes (as in duplicates)? I don't think they want the dupes removed in the table so you can just use `props.results.map`.

2020-07-17 05:07 UTC, haydenf commented on src/components/ResultsTable.tsx
> +                        {uniqueResults.map((result, index) => {
I don't think I  added uniqueResults, it was in the previous edition of the results table. I just pulled from this branch and my version before the pull had it declared which is weird

2020-07-18 00:20 UTC, johnEthicalTechnology approved these changes

2020-07-18 00:20 UTC, merged